# Generated by Django 4.1.7 on 2023-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='persona',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
