# Generated by Django 4.1.7 on 2023-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_persona_age_persona_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Capacidades',
            field=models.CharField(default=[], max_length=200),
        ),
    ]
